--- #YAML:1.0
name:                HTML-FromANSI
version:             2.03
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    HTML::Entities:                0.01
    Term::VT102::Boundless:        0.03
    Test::More:                    0.11
    Test::use::ok:                 0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
